# Generated by Django 5.0.1 on 2024-01-31 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signup", "0002_user_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="idx",
            new_name="id",
        ),
    ]
