# Generated by Django 5.0.1 on 2024-02-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup", "0004_enterprise_company_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("e", "Enterprise"), ("i", "Individual"), ("a", "Admin")],
                max_length=10,
            ),
        ),
    ]
